### ISSUE TITLE
Host's buffer gets cleared when client connects

### ISSUE THREAD

**Issue by rosehuds** [jbyuki/instant.nvim#10]
When a client connects to a session, the host's buffer becomes empty, desyncing them.
[demonstrated on asciinema](https://asciinema.org/a/qFP7Z9KiYjsK5X8jM3uZxWgNs?t=10s)
using neovim 0.5.0

**Comment by jbyuki** [comment]
Thank you for the issue. I can reproduce it. This is probably caused because it's trying to open a file which is already opened in another neovim instance. Try changing the current working directory in the second instance.

**Comment by rosehuds** [comment]
I don't think that's the problem, because iirc I found the issue when testing across two separate machines. I will double check though

**Comment by rosehuds** [comment]
In the original recording the neovim instances are already running in two separate working directories ~/work/instant and ~/work/instant2

**Comment by jbyuki** [comment]
Good point, let me see in more details when I have some spare time.
