### ISSUE TITLE
When starting server it doesn't need args but joining session errors

### ISSUE THREAD

**Issue by narodnik** [jbyuki/instant.nvim#11]
Hi, following the guide for the first time was confusing until I saw the gif image.

Basically you use :InstantStartServer with no args, but InstantStartSession requires args otherwise I get a confusing error. To make it work, I had to use :InstantStartSession 127.0.0.1 8080.

Consider changing the defaults or at least adding a line in the README, and making the error message more informative.

Thanks a lot for this amazing tool

**Comment by jbyuki** [comment]
Hi,
Thank you for the issue.
If you're still willing to help others, consider modifying the README so that it makes it more clear. I will merge it afterwards.
