### ISSUE TITLE
Error executing vim.schedule lua callback: ...im/plugged/instant.nvim/lua/instant/websocket_client.lua:92: There was an error during connection: ETIMEDOUT

### ISSUE THREAD

**Issue by Syrup** [jbyuki/instant.nvim#15]
I want to host a remote server on heroku and the setup runs fine, the problem is when I want to use `:InstantStartServer ip port` and `InstantStartSession ip port`it return an error (i have also tried `:InstantStartSingle ip port`) and the result is the same. I'm pretty sure I've entered the ip and port correctly because in the heroku log it says `Peer connected` and no errors.

error:
`
Error executing vim.schedule lua callback: ...im/plugged/instant.nvim/lua/inst
ant/websocket_client.lua:92: There was an error during connection: ETIMEDOUT
      stack traceback:                                                                      [C]: in function 'error'                                                      ...im/plugged/instant.nvim/lua/instant/websocket_client.lua:92: in function 'cb'                                                                            vim.lua:285: in function <vim.lua:285>
`
Neovim: v0.6.1

**Comment by jbyuki** [comment]
If the server is already running on the cloud, you don't need to start a server again in Neovim. You can just copy the url and go ahead and start a session using `:InstantStartSingle [url]` or `:InstantStartSession [url]`. The client should connect to the remote server.
I hope that clear things out.

**Comment by Syrup** [comment]
Yes! it works thanks for replying to my issue
