### ISSUE TITLE
Enhancement: Use extmark instead of deprecated virtual text.

### ISSUE THREAD

**Issue by rag-hav** [jbyuki/instant.nvim#17]
`vim.api.nvim_set_virtual_text` has been deprecated in Neovim. The API that replaces it `vim.api.nvim_set_extmark` is more feature-rich and allows for virtual text on the right side of the window.

Like this-

![image](https://user-images.githubusercontent.com/60528983/175783479-46a06617-2b20-4145-9fe5-cf1475b0c13f.png)

The screenshot if after making [changes](https://github.com/rag-hav/instant.nvim/commit/4cc622636c1c4b262c33ac5475b08929443d0087) in the `lua/instant.lua` file. I do not understand the src code (or ntangle) enough to create a PR for this.

**Comment by jbyuki** [comment]
Thank you for looking into this. That's too bad you made the changes but can't merge them into the main repository. 

I will try to check your fork, do the changes and credit you somehow.

In case, you still want to look into ntangle, it's really not that hard to use. I'm using it mainly as an experiment to try to explore literate programming. But I'm aware it's not for everybody. When ntangle.nvim is installed, you could in principle modify the lua.t files and the changes will be reflected in the lua files. For minor modifications, you don't need to understand the syntax of ntangle. I'm saying all this for any future changes, but I will do this one in a moment.
