### ISSUE TITLE
How to deal with jump server?

### ISSUE THREAD

**Issue by ysl2** [jbyuki/instant.nvim#33]
I always use this command to login server (just for example):

```
ssh hello@111.222.333.444 -p 5566
```

In fact, when I login, it drives me to another machine `777.888.999.000` (cannot be public beacuse of security).

Now in the `777.888.999.000` machine, I use `:InstantStartServer 127.0.0.1 7890` to start a server.

In my personal computer, I want to connect the started server `777.888.999.000` but I cannot directly connect it beacuse it cannot be public, must login  by the jump server `111.222.333.444` and in the port `5566`

So I try to use `:InstantStartSession 111.222.333.444:5566 7890` but it doesn't work, obviously.

How should I do to deal with the jump server?

**Comment by ghost** [comment]
`:InstantStartSession 111.222.333.444:5566 7890` is invalid because `111.222.333.444:5566` isn't a valid IP address, you need to make your setup accessable throw an IP address, not an ssh connection throw a port of an IP address.

instant.nvim can't really do anything about that.
