### ISSUE TITLE
Other editors

### ISSUE THREAD

**Issue by NullSense** [jbyuki/instant.nvim#4]
I'm not sure if this is out of the scope of this plugin, but is it possible to connect to other editors? Looking at the docs, it seems that it's not. Would be awesome to connect to coworkers that are using vscode/intellij plugins.

**Comment by jbyuki** [comment]
In the current state, it's not possible. Unless there is a real demand, I don't think I will implement it as I'm not really familiar with the other IDEs plugin development. You might consider Floobits which actually supports cross editor support. I'm not sure if vscode is included though.
