### ISSUE TITLE
InstantStartSession always caueses ECONNREFUSED. Tried different hosts and ports. Tried disabling firewall.

### ISSUE THREAD

**Issue by DasOhmoff** [jbyuki/instant.nvim#8]
Hello, thank you for your support and for this plugin.

I am working on a windows 10 machine. I tried to run this plugin using the `:InstantStartSession 127.0.0.1 8080` command, but the only result I ever get is:
```
Error executing vim.schedule lua callback: ...es\plugged\instant.nvim\lua\instant\websocket_client.lua:92: There was an error during connection: ECONNREFUSED
Disconnected.
```

I tried using different hosts and ports. I also tried turning off the windows firewall, but it does not seem to help. How can I fix this?

**Comment by jbyuki** [comment]
Thank you for the issue.

Did you first start a server where `instant.nvim` can connect to? 
Try something along the lines:

* Open a nvim instance and do `:InstantStartServer 127.0.0.1 8080`.
* Use `:InstantStartSession 127.0.0.1 8080` in the same instance.
   This should connect the client to the server and display `Connected.`
* Open another nvim instance and do `:InstantJoinSession 127.0.0.1 8080`

The OS should not be an issue as I'm also using Windows 10.

**Comment by DasOhmoff** [comment]
Oh, you are right, I completely missed that. Thank you for your help.
